obj-$(CONFIG_CHARGER_SMB328)	+= sec_charger.o

obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_fuelgauge.o		\
				sec_battery.o


obj-$(CONFIG_FUELGAUGE_88PM822)		+= 88pm80x_fuelgauge.o

obj-$(CONFIG_CHARGER_SMB328)	+= smb328_charger.o
