#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_SYMLINK_CORE)	+= sensors_core.o
obj-$(CONFIG_SENSORS_ACCELOMETER_BMA25X)	+= bma255.o
